apiVersion: v1
data:
  rootUsername: $(echo -n 'username' | base64)
  rootPassword: $(echo -n 'password' | base64)
  database: $(echo -n 'photodump' | base64)
  url: $(echo -n 'svc-mongodb.photo-dump.svc.cluster.local:27017' | base64)
kind: Secret
metadata:
  name: mongodb-custom-creds
  namespace: mongodb-custom
type: Opaque