apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
  namespace: dns
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    daemon=300
    syslog=yes
    use=web
    web=https://cloudflare.com/cdn-cgi/trace
    web-skip='ip='
    ssl=yes

    protocol=cloudflare
    zone=example.com
    ttl=1
    password={cloudflare-api-token}
    example.com
