apiVersion: v1
kind: Namespace
metadata:
  name: browserless
  labels:
    name: browserless
---
apiVersion: v1
kind: Service
metadata:
  name: chrome-entrypoint
  namespace: browserless
spec:
  type: NodePort
  selector:
    app: browserless-chrome
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless-chrome
  namespace: browserless
  labels:
    app: browserless-chrome
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: browserless-chrome
  template:
    metadata:
      labels:
        app: browserless-chrome
    spec:
      containers:
        - name: browserless-chrome
          image: browserless/chrome
          ports:
          - containerPort: 3000
            name: driver-access
          volumeMounts:
            - mountPath: "/dev/shm"
              name: dshm
          env:
          - name: CONNECTION_TIMEOUT
            value: "3600000"
          resources:
            requests:
              cpu: 2
              memory: 2Gi
            limits:
              cpu: 4
              memory: 8Gi
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
