apiVersion: v1
kind: Namespace
metadata:
  name: mysql-custom
  labels:
    name: mysql-custom
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: mysql-custom
spec:
  storageClassName: nfs-crucial
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-files
  namespace: mysql-custom
spec:
  storageClassName: nfs-crucial
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql-custom
spec:
  selector:
    matchLabels:
      app: mysql-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      securityContext:
        fsGroup: 100
      containers:
      - image: mysql:5.6
        name: mysql-deployment
        securityContext:
          runAsUser: 4000
          runAsGroup: 100
          allowPrivilegeEscalation: false
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: rootpass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-files
          mountPath: /var/lib/mysql-files
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-mysql
      - name: mysql-files
        persistentVolumeClaim:
          claimName: pvc-mysql-files
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-custom-svc
  namespace: mysql-custom
spec:
  type: NodePort
  selector:
    app: mysql-deployment
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
    protocol: TCP




