apiVersion: v1
data:
  rootpass: $(echo -n 'rootpassword' | base64)
kind: Secret
metadata:
  name: mysql-credentials
  namespace: mysql-custom
type: Opaque
---
apiVersion: v1
data:
  username: $(echo -n 'username' | base64)
  password: $(echo -n 'password' | base64)
  dburl: $(echo -n 'mysql.mysql-custom.cluster.local:3306/parts_direct' | base64)
kind: Secret
metadata:
  name: mysql-credentials-database
  namespace: mysql-custom
type: Opaque