apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 2.1.2
      helm:
        releaseName: tempo
        valueFiles:
          - $values/monitoring/helm-values/tempo-values.yaml
    - repoURL: git@github.com:dwilson2547/cluster_config.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
