apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build-sim
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dwilson2547/drone-build-sim.git
    targetRevision: main
    path: helm/build-sim
  destination:
    server: https://kubernetes.default.svc
    namespace: build-sim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
