apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://downloads.apache.org/flink/flink-kubernetes-operator-1.14.0/
      chart: flink-kubernetes-operator
      targetRevision: 1.14.0
      helm:
        releaseName: flink-operator
        valueFiles:
          - $values/flink-operator/values.yaml
    - repoURL: git@github.com:dwilson2547/cluster_config.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: flink-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
