apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gyopart-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dwilson2547/gyopart.git
    targetRevision: dev
    path: helm/gyopart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gyopart-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
