# First install prometheus-operator: 
# 
# helm install coreos/prometheus-operator --name prometheus-operator
#

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-node1-exporter
  # Namespace of prometheus operator
  namespace: observability
  labels:
    prometheus: mon
spec:
  namespaceSelector:
    matchNames:
    - observability
  selector:
    matchLabels:
      app: ai-node1-exporter
  endpoints:
  - port: metrics
    interval: 10s