apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kube-prometheus-external-scrape
  namespace: observability
  labels:
    app: kube-prometheus-external-scrape
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
    prometheus: system-monitoring-prometheus
    release: kube-prom-stack
spec:
  staticConfigs:
    - labels:
        job: kube-prometheus-external-scrape
      targets:
        - "192.168.0.80:9100"
        - "192.168.0.80:9400"
        - "192.168.0.15:9100"
        - "192.168.0.30:9119"
        - "192.168.0.31:9617"