apiVersion: v1
kind: Secret
metadata:
  name: rtk-caster-secret
  namespace: rtk-caster
type: Opaque
stringData:
  source_password: "CHANGE_ME_SOURCE_PASSWORD"
  client_username: "rtk-client"
  client_password: "CHANGE_ME_CLIENT_PASSWORD"
