apiVersion: v1
kind: Secret
metadata:
  name: rtk-caster-secret
  namespace: rtk-caster
type: Opaque
stringData:
  source_password: "CHANGE_ME_SOURCE_PASSWORD"
  client_username: "rtk-client"
  client_password: "CHANGE_ME_CLIENT_PASSWORD"
  rtk2go_host: "rtk2go.com"
  rtk2go_port: "2101"
  rtk2go_mountpoint: "CHANGE_ME_MOUNTPOINT"
  rtk2go_source_password: "CHANGE_ME_RTK2GO_SOURCE_PASSWORD"
